---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - frontend.yaml
images:
  - name: index.docker.io/ambrosiaaaaa/my-frontend-image
    newName: index.docker.io/ambrosiaaaaa/my-frontend-image
    newTag: "v0.0.5"
