---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  namespace: details
spec:
  replicas: 1
  selector:
    matchLabels:
      name: details
  template:
    metadata:
      labels:
        name: details
    spec:
      containers:
      - name: details
        image: index.docker.io/ambrosiaaaaa/my-details-image:{{image-tag}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: details
spec:
  ports:
  - name: "details"
    port: 9080
    targetPort: 9080
  selector:
    name: details
