---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: productpage
    namespace: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      name: productpage
  template:
    metadata:
      labels:
        name: "productpage"
    spec:
      containers:
      - name: productpage
        image: index.docker.io/tadeuuuuu/{{ image-productpage }} 
        imagePullPolicy: IfNotPresent
        env:
        - name: DETAILS_HOSTNAME
          value: details
        - name: REVIEWS_HOSTNAME
          value: reviews
        ports:
        - containerPort: 9080
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: productpage
spec:
  ports:
  - name: "productpage-service"
    port: 9080
    targetPort: 9080
  selector:
    name: productpage
status:
  loadBalancer: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: productpage
  namespace: productpage
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: productpage
    scaleDown:
      stabilizationWindowSeconds: 15 # seconds wait before scaling down
      policies:
      - type: Pods
        value: 1 # scale down 1 pod at a time
        periodSeconds: 20 # seconds wait before another scale down allowed
      selectPolicy: Max