---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: productpage
    namespace: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      name: productpage
  template:
    metadata:
      labels:
        name: "productpage"
    spec:
      containers:
      - name: productpage
        image: index.docker.io/ambrosiaaaaa/my-productpage-image:{{image-tag}}
        imagePullPolicy: IfNotPresent
        env:
        - name: DETAILS_HOSTNAME
          value: details.details.svc.cluster.local
        - name: RATINGS_HOSTNAME
          value: ratings.ratings.svc.cluster.local
        - name: REVIEWS_HOSTNAME
          value: reviews.reviews.svc.cluster.local
        ports:
        - containerPort: 9080
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: productpage
  namespace: productpage
spec:
  ports:
  - name: "productpage-service"
    port: 9080
    targetPort: 9080
  selector:
    name: productpage

