---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - reviews.yaml
images:
  - name: index.docker.io/ambrosiaaaaa/my-reviews-image
    newName: index.docker.io/ambrosiaaaaa/my-reviews-image
    newTag: "v0.1.0"
