---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ratings
  template:
    metadata:
      labels:
        name: ratings
    spec:
      containers:
      - name: ratings
        image: index.docker.io/ambrosiaaaaa/my-ratings-image:{{image-tag}}
        ports:
        - containerPort: 9080
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: ratings
                key: db_host
          - name: MYSQL_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: ratings
                key: db_port
          - name: MYSQL_DB_USER
            valueFrom:
              configMapKeyRef:
                name: ratings
                key: user

          - name: MYSQL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ratings
                key: db_pass
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: ratings
spec:
  ports:
  - name: "ratings"
    port: 9080
    targetPort: 9080
  selector:
    name: ratings
