apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql
  template:
    metadata:
      annotations:
      labels:
        name: mysql
    spec:
      containers:
      - name: mysql
        image: index.docker.io/{{ image-mysql }} 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: hash123
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - name: "mysql-service"
      port: 3306
      targetPort: 3306
  type: ClusterIP 
  selector:
    name: mysql
