apiVersion: apps/v1
kind: Deployment
metadata:
    name: productpage
spec:
  replicas: 1
  selector:
    matchLabels:
      name: productpage
  template:
    metadata:
      labels:
        name: "productpage"
    spec:
      containers:
      - name: productpage
        image: index.docker.io/tadeuuuuu/{{ image-productpage }} 
        imagePullPolicy: IfNotPresent
        env:
        - name: DETAILS_HOSTNAME
          value: details
        - name: REVIEWS_HOSTNAME
          value: reviews
        ports:
        - containerPort: 9080
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
---
apiVersion: v1
kind: Service
metadata:
  name: productpage-service
spec:
  ports:
  - name: "productpage-service"
    port: 9080
    targetPort: 9080
  selector:
    name: productpage
status:
  loadBalancer: {}
