---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  namespace: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ratings
  template:
    metadata:
      labels:
        name: ratings
    spec:
      containers:
      - name: ratings
        image: index.docker.io/{{ image-ratings }} 
        ports:
        - containerPort: 9080
        imagePullPolicy: IfNotPresent
        env:
        - name: DB_TYPE 
          value: mysql
        - name: MYSQL_DB_HOST
          value: localhost
        - name: MYSQL_DB_PASSWORD
          value: hash123
        - name: MYSQL_DB_PORT
          value: "3306"
        - name: MYSQL_DB_USER
          value: root
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: ratings
spec:
  ports:
  - name: "ratings"
    port: 9080
    targetPort: 9080
  selector:
    name: ratings
status:
  loadBalancer: {}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ratings
  namespace: ratings
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 50
        type: Utilization
    type: Resource
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ratings
    scaleDown:
      stabilizationWindowSeconds: 15 # seconds wait before scaling down
      policies:
      - type: Pods
        value: 1 # scale down 1 pod at a time
        periodSeconds: 20 # seconds wait before another scale down allowed
      selectPolicy: Max
